[colors]

[colors.primary]
background = "#ffffff" 
foreground = "#000000"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#000000"
yellow = "#ffc30b"
blue = "#000000"
magenta = "#000000"
cyan = "#000000"
white = "#eeeeee"

[colors.cursor]
text = "#ffffff"
cursor = "#0000ff"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#000000"
background = "#ffd700"

[colors.search.focused_match]
foreground = "#ffffff"
background = "#0000ff"

[colors.line_indicator]
foreground = "#eeeeee"
background = "#000000"

[colors.footer_bar]
foreground = "#eeeeee"
background = "#000000"
